### ISSUE TITLE
Symbol's value as variable is void: package-archives

### ISSUE THREAD

**Issue by juniorxxue** [zerolee/.emacs.d#1]
配置中package-archives好像没定义呀，我的是Emacs 26.1，clone了一下你的配置，报这个错误。
grep了一下emacs.d，确实只有这一句。
`grep -r 'package-archives' .emacs.d/*`

`.emacs.d/Configurations/emacs-std.el:(add-to-list 'package-archives '("melpa" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/"))`

是不同版本的`package.el`有区别嘛。谢谢^ ^

**Comment by zerolee** [comment]
对，是不同版本 package.el 的区别，我用的 emacs 是 master 版本的（也就是 27）
你可以尝试在 init.el 开头加上 

(require 'package)
(package-initialize)
或者 
(package-initialize)

然后记得把 emacs-std.el 这个文件里面的
```emacs-lisp
 (add-to-list 'package-archives '("melpa" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/"))
```
这句话替换成
```emacs-lisp
  (setq package-archives '(("gnu"   . "http://elpa.emacs-china.org/gnu/")
                           ("melpa" . "http://elpa.emacs-china.org/melpa/")))
````
因为清华源同步出了点问题

最后，early-init.el 文件里的
```emacs-lisp
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
```
不起作用也是因为只有 Emacs 27 才支持 early-init.el，把他们移动到其他地方就可以了，比如 emacs-std.el 或者其他什么的

**Comment by juniorxxue** [comment]
Problem Solved~
